services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - "db-data:/var/lib/mysql:rw"
  app:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
volumes:
  db-data: {}